DELIMITER $$

DROP TRIGGER IF EXISTS `hardware_changes_delete` $$

CREATE TRIGGER `hardware_changes_delete` AFTER DELETE ON `hardware` 
FOR EACH ROW BEGIN
		UPDATE `hardware_changes` 
			SET
				DELETED=TRUE,
				NOTIFIED=FALSE,
				LAST_TS=CURRENT_TIMESTAMP
			WHERE 
				UUID=OLD.UUID
                AND HARDWARE_ID=OLD.ID
				AND	PROCESSORT=OLD.PROCESSORT
				AND	PROCESSORN=OLD.PROCESSORN;

END$$

DELIMITER ;
