DELIMITER $$

DROP TABLE IF EXISTS `hardware_changes` $$

CREATE TABLE `hardware_changes` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HARDWARE_ID` int(11) NOT NULL,
  `DEVICEID` varchar(255) NOT NULL,
  `PROCESSORT` varchar(255) DEFAULT NULL,
  `PROCESSORN` smallint(6) DEFAULT NULL,
  `UUID` varchar(255) NOT NULL,
  `INSERT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_TS` timestamp,
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `NOTIFIED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`HARDWARE_ID`,`DEVICEID`,`PROCESSORT`,`PROCESSORN`),
  KEY `PROCESSORT` (`PROCESSORT`),
  KEY `DEVICEID` (`DEVICEID`),
  KEY `UUID` (`UUID`),
  KEY `HARDWARE_ID` (`HARDWARE_ID`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8$$

DELIMITER ;

