delimiter $$

DROP TABLE IF EXISTS `memories_changes` $$

CREATE TABLE `memories_changes` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEMORY_ID` int(11) NOT NULL,
  `HARDWARE_ID` int(11) NOT NULL,
  `CAPTION` varchar(255) NOT NULL DEFAULT '',
  `DESCRIPTION` varchar(255) NOT NULL DEFAULT '',
  `CAPACITY` varchar(255) NOT NULL DEFAULT '',
  `TYPE` varchar(255) DEFAULT NULL,
  `SPEED` varchar(255) DEFAULT NULL,
  `NUMSLOTS` smallint(6) DEFAULT NULL,
  `SERIALNUMBER` varchar(255) NOT NULL DEFAULT '',
  `INSERT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `NOTIFIED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`HARDWARE_ID`,`CAPTION`,`DESCRIPTION`,`CAPACITY`,`SERIALNUMBER`),
  KEY `CAPTION` (`CAPTION`),
  KEY `DESCRIPTION` (`DESCRIPTION`),
  KEY `HARDWARE_ID` (`HARDWARE_ID`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

DELIMITER ;