DELIMITER $$

DROP TRIGGER IF EXISTS `memories_changes_delete` $$

CREATE TRIGGER `memories_changes_delete` AFTER DELETE ON `memories` 
FOR EACH ROW BEGIN
		UPDATE `memories_changes` 
			SET
				DELETED=TRUE,
				NOTIFIED=FALSE,
				LAST_TS=CURRENT_TIMESTAMP
			WHERE 
				MEMORY_ID=OLD.ID
				AND HARDWARE_ID=OLD.HARDWARE_ID
				AND	CAPTION=OLD.CAPTION
				AND	DESCRIPTION=OLD.DESCRIPTION
				AND	CAPACITY=OLD.CAPACITY
				AND	SERIALNUMBER=OLD.SERIALNUMBER;

END$$

DELIMITER ;
