DELIMITER $$

DROP TRIGGER IF EXISTS `monitors_changes_delete` $$

CREATE TRIGGER `monitors_changes_delete` AFTER DELETE ON `monitors` 
FOR EACH ROW BEGIN
		UPDATE `monitors_changes` 
			SET
				DELETED=TRUE,
				NOTIFIED=FALSE,
				LAST_TS=CURRENT_TIMESTAMP
			WHERE 
				MONITOR_ID=OLD.ID
				AND HARDWARE_ID=OLD.HARDWARE_ID
				AND	MANUFACTURER=OLD.MANUFACTURER
				AND	CAPTION=OLD.CAPTION
				AND	SERIAL=OLD.SERIAL;

END$$

DELIMITER ;
