DELIMITER $$

DROP TABLE IF EXISTS `monitors_changes` $$

CREATE TABLE `monitors_changes` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MONITOR_ID` int(11) NOT NULL,
  `HARDWARE_ID` int(11) NOT NULL,
  `MANUFACTURER` varchar(255) DEFAULT NULL,
  `CAPTION` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `SERIAL` varchar(255) DEFAULT NULL,
  `INSERT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_TS` timestamp,
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `NOTIFIED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`HARDWARE_ID`,`MANUFACTURER`,`CAPTION`,`SERIAL`),
  KEY `MANUFACTURER` (`MANUFACTURER`),
  KEY `DESCRIPTION` (`DESCRIPTION`),
  KEY `CAPTION` (`CAPTION`),
  KEY `HARDWARE_ID` (`HARDWARE_ID`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8$$

DELIMITER ;