DELIMITER $$

DROP TRIGGER IF EXISTS `monitors_changes_insert` $$

CREATE TRIGGER `monitors_changes_insert` AFTER INSERT ON `monitors` 
FOR EACH ROW BEGIN
		INSERT INTO `monitors_changes` 
			SET 
				MONITOR_ID=NEW.ID,
				HARDWARE_ID=NEW.HARDWARE_ID,
				MANUFACTURER=NEW.MANUFACTURER,
				CAPTION=NEW.CAPTION,
				DESCRIPTION=NEW.DESCRIPTION,
				SERIAL=NEW.SERIAL
			ON DUPLICATE KEY UPDATE
				MONITOR_ID=NEW.ID,
				DELETED=FALSE;
END$$

DELIMITER ;
