DELIMITER $$

DROP TRIGGER IF EXISTS `softwares_changes_insert` $$

CREATE TRIGGER `softwares_changes_insert` AFTER INSERT ON `softwares` 
FOR EACH ROW BEGIN
		INSERT INTO `softwares_changes` 
			SET 
				SOFTWARE_ID=NEW.ID,
				HARDWARE_ID=NEW.HARDWARE_ID,
				NAME=NEW.NAME,
				VERSION=NEW.VERSION,
				FILESIZE=NEW.FILESIZE,
				INSTALLDATE=NEW.INSTALLDATE
			ON DUPLICATE KEY UPDATE
				SOFTWARE_ID=NEW.ID,
				VERSION=NEW.VERSION,
				DELETED=FALSE;
END$$

DELIMITER ;

