DELIMITER $$

DROP TABLE IF EXISTS `softwares_changes` $$

CREATE TABLE `softwares_changes` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SOFTWARE_ID` int(11) NOT NULL,
  `HARDWARE_ID` int(11) NOT NULL,
  `NAME` varchar(255) NOT NULL DEFAULT '',
  `VERSION` varchar(255) NOT NULL DEFAULT '',
  `FILESIZE` int(11) DEFAULT '0',
  `INSTALLDATE` datetime DEFAULT NULL,
  `INSERT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_TS` timestamp,
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `NOTIFIED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`HARDWARE_ID`,`NAME`),
  KEY `NAME` (`NAME`),
  KEY `HARDWARE_ID` (`HARDWARE_ID`),
  KEY `VERSION` (`VERSION`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8$$

DELIMITER ;
