DELIMITER $$

DROP TABLE IF EXISTS `storages_changes` $$

CREATE TABLE `storages_changes` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STORAGE_ID` int(11) NOT NULL,
  `HARDWARE_ID` int(11) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `MODEL` varchar(255) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `DISKSIZE` int(11) DEFAULT NULL,
  `SERIALNUMBER` varchar(255) DEFAULT NULL,
  `INSERT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_TS` timestamp,
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  `NOTIFIED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`HARDWARE_ID`,`NAME`,`MODEL`,`SERIALNUMBER`),
  KEY `NAME` (`NAME`),
  KEY `MODEL` (`MODEL`),
  KEY `HARDWARE_ID` (`HARDWARE_ID`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8$$

DELIMITER ;