DELIMITER $$

DROP TRIGGER IF EXISTS `storages_changes_delete` $$

CREATE TRIGGER `storages_changes_delete` AFTER DELETE ON `storages` 
FOR EACH ROW BEGIN
		UPDATE `storages_changes` 
			SET
				DELETED=TRUE,
				NOTIFIED=FALSE,
				LAST_TS=CURRENT_TIMESTAMP
			WHERE 
				STORAGE_ID=OLD.ID
				AND HARDWARE_ID=OLD.HARDWARE_ID
				AND	NAME=OLD.NAME
				AND	MODEL=OLD.MODEL
				AND	SERIALNUMBER=OLD.SERIALNUMBER;

END$$

DELIMITER ;
